import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "../components/header/inde";
import { Carousel } from "@/components/ui/carousel";






export const metadata: Metadata = {
  title: "SL baterias",
  description: "Generated by sl baterias",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={"antialiased"}
      >

        <Carousel/>
        <Header/>
        {children}
      </body>
    </html>
  );
}
